nodeLinker: node-modules

catalog:
  "rescript": 12.2.0
  "sury": 11.0.0-alpha.4
  "sury-ppx": 11.0.0-alpha.4
  "dotenv": 17.2.3
  "@vitest/coverage-v8": 4.1.7
  "vite": ^7.3.2
  "vitest": 4.1.7
  "rescript-vitest": 2.1.1
  "@rescript/webapi": "*"
