nodeLinker: node-modules

catalog:
  "rescript": 12.3.0
  "sury": 11.0.0-alpha.8
  "sury-ppx": 11.0.0-alpha.8
  "dotenv": 17.2.3
  "@vitest/coverage-v8": 4.1.8
  "vite": ^7.3.2
  "vitest": 4.1.8
  "rescript-vitest": 2.1.1
  "@rescript/webapi": "*"

packageExtensions:
  "@astrojs/language-server@*":
    dependencies:
      "typescript": "*"
  "@astrojs/preact@*":
    dependencies:
      "@babel/core": "^7.0.0"
  "@preact/preset-vite@*":
    dependencies:
      "preact": "*"
  "@sentry/nextjs@*":
    dependencies:
      "@opentelemetry/core": "^2.6.1"
      "@opentelemetry/sdk-trace-base": "^2.6.1"
    peerDependencies:
      "react": "^16.14.0 || 17.x || 18.x || 19.x"
  "@sentry/webpack-plugin@*":
    peerDependenciesMeta:
      "webpack":
        optional: true
