[tools]
node="24.9.0"
pnpm="11.9.0"
elixir="1.20.0-otp-29"
erlang="29.0.1"
elixir-ls="0.30.0"
mprocs="0.7.1"
mkcert="1.4.4"
"npm:@rescript/language-server"="latest"
"npm:rescript"="latest"
"npm:corepack"="latest"
"npm:@tailwindcss/language-server"="latest"
"npm:vscode-langservers-extracted"="latest"
"npm:@biomejs/biome"="latest"
"npm:typescript-language-server" = "latest"
lefthook="latest"

[env]
MIX_OS_DEPS_COMPILE_PARTITION_COUNT = "1"
