# Frontman Server
# Copyright (C) 2025 Frontman AI
#
# Licensed under the AGPL-3.0 — see LICENSE for details.
# Additional terms apply — see AI-SUPPLEMENTARY-TERMS.md

defmodule FrontmanServer.Providers.OpenAIOAuth do
  @moduledoc """
  Handles OAuth authentication for OpenAI accounts.

  Implements the Device Auth flow against OpenAI's auth server:
  1. Request a device code (user_code) from OpenAI
  2. User opens https://auth.openai.com/codex/device and enters the code
  3. Server polls OpenAI until user authorizes → receives authorization_code + PKCE
  4. Exchange authorization_code for access/refresh/id tokens
  5. Extract chatgpt_account_id from JWT claims
  6. Refresh tokens when expired

  Uses the same public OAuth client_id as Codex CLI.
  The device auth flow is required because this client_id only allows
  http://localhost:* redirect URIs (it's a native/public client).
  """

  require Logger

  @client_id Application.compile_env!(:frontman_server, [__MODULE__, :client_id])
  @issuer Application.compile_env!(:frontman_server, [__MODULE__, :issuer])
  @token_url "#{@issuer}/oauth/token"
  @req_options Application.compile_env(:frontman_server, [__MODULE__, :req_options], [])

  @doc """
  Step 1: Request a device code from OpenAI.

  Returns `{:ok, %{device_auth_id: ..., user_code: ..., interval: ..., verification_url: ...}}`
  or `{:error, reason}`.

  The `interval` is the polling interval in seconds.
  """
  def request_device_code do
    body = Jason.encode!(%{"client_id" => @client_id})

    headers = [
      {"content-type", "application/json"},
      {"accept", "application/json"}
    ]

    case Req.post(
           "#{@issuer}/api/accounts/deviceauth/usercode",
           [body: body, headers: headers] ++ @req_options
         ) do
      {:ok, %Req.Response{status: status, body: response_body}} when status in 200..299 ->
        device_auth_id = response_body["device_auth_id"]
        user_code = response_body["user_code"] || response_body["usercode"]
        interval = parse_interval(response_body["interval"])

        if device_auth_id && user_code do
          {:ok,
           %{
             device_auth_id: device_auth_id,
             user_code: user_code,
             interval: interval,
             verification_url: "#{@issuer}/codex/device"
           }}
        else
          Logger.error("OpenAI device code response missing fields: #{inspect(response_body)}")
          {:error, :invalid_response}
        end

      {:ok, %Req.Response{status: 404}} ->
        {:error, :device_auth_not_enabled}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error("OpenAI device code request failed: status=#{status}, body=#{inspect(body)}")

        {:error, {:device_code_failed, status, body}}

      {:error, reason} ->
        Logger.error("OpenAI device code request error: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Step 2: Poll OpenAI to check if the user has authorized.

  Returns:
  - `{:ok, %{authorization_code: ..., code_verifier: ...}}` when user has authorized
  - `{:pending}` when user hasn't authorized yet
  - `{:error, reason}` on failure

  The `code_verifier` is server-generated by OpenAI (not standard PKCE).
  """
  def poll_device_token(device_auth_id, user_code) do
    body = Jason.encode!(%{"device_auth_id" => device_auth_id, "user_code" => user_code})

    headers = [
      {"content-type", "application/json"},
      {"accept", "application/json"}
    ]

    case Req.post(
           "#{@issuer}/api/accounts/deviceauth/token",
           [body: body, headers: headers] ++ @req_options
         ) do
      {:ok, %Req.Response{status: 200, body: response_body}} ->
        authorization_code = response_body["authorization_code"]
        code_verifier = response_body["code_verifier"]

        if authorization_code && code_verifier do
          {:ok, %{authorization_code: authorization_code, code_verifier: code_verifier}}
        else
          Logger.error("OpenAI device token response missing fields: #{inspect(response_body)}")

          {:error, :invalid_response}
        end

      {:ok, %Req.Response{status: status}} when status in [403, 404] ->
        # User hasn't authorized yet
        {:pending}

      {:ok, %Req.Response{status: 401, body: body}} ->
        Logger.error("OpenAI device auth declined: #{inspect(body)}")
        {:error, :authorization_declined}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error("OpenAI device token poll failed: status=#{status}, body=#{inspect(body)}")

        {:error, {:poll_failed, status, body}}

      {:error, reason} ->
        Logger.error("OpenAI device token poll request error: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Step 3: Exchange the authorization code (from device flow) for tokens.

  Uses the server-generated `code_verifier` from the poll response and
  OpenAI's device auth callback as the redirect_uri.

  Returns `{:ok, %{access_token: ..., refresh_token: ..., id_token: ..., expires_in: ...}}`
  or `{:error, reason}`.
  """
  def exchange_device_code(authorization_code, code_verifier) do
    body =
      URI.encode_query(%{
        "grant_type" => "authorization_code",
        "code" => authorization_code,
        "redirect_uri" => "#{@issuer}/deviceauth/callback",
        "client_id" => @client_id,
        "code_verifier" => code_verifier
      })

    headers = [
      {"content-type", "application/x-www-form-urlencoded"},
      {"accept", "application/json"}
    ]

    case Req.post(@token_url, [body: body, headers: headers] ++ @req_options) do
      {:ok,
       %Req.Response{
         status: 200,
         body:
           %{
             "access_token" => access_token,
             "id_token" => id_token,
             "refresh_token" => refresh_token
           } = response_body
       }} ->
        {:ok,
         %{
           access_token: access_token,
           refresh_token: refresh_token,
           id_token: id_token,
           expires_in: response_body["expires_in"]
         }}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error(
          "OpenAI device code exchange failed: status=#{status}, body=#{inspect(body)}"
        )

        {:error, {:token_exchange_failed, status, body}}

      {:error, reason} ->
        Logger.error("OpenAI device code exchange request failed: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Refreshes an access token using the refresh token.

  Returns `{:ok, %{access_token: ..., refresh_token: ..., id_token: ..., expires_in: ...}}`
  or `{:error, reason}`.
  """
  def refresh_token(refresh_token) do
    body =
      URI.encode_query(%{
        "grant_type" => "refresh_token",
        "refresh_token" => refresh_token,
        "client_id" => @client_id
      })

    headers = [
      {"content-type", "application/x-www-form-urlencoded"},
      {"accept", "application/json"}
    ]

    case Req.post(@token_url, [body: body, headers: headers] ++ @req_options) do
      {:ok, %Req.Response{status: 200, body: response_body}} ->
        {:ok,
         %{
           access_token: response_body["access_token"],
           refresh_token: response_body["refresh_token"],
           id_token: response_body["id_token"],
           expires_in: response_body["expires_in"]
         }}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error("OpenAI OAuth token refresh failed: status=#{status}, body=#{inspect(body)}")

        {:error, {:token_refresh_failed, status, body}}

      {:error, reason} ->
        Logger.error("OpenAI OAuth token refresh request failed: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Extracts the account ID from the token response id_token.
  """
  def extract_account_id_from_tokens(%{id_token: id_token}) do
    extract_account_id(id_token)
  end

  # Private helpers

  defp extract_account_id(jwt) when is_binary(jwt) do
    {:ok, claims} = decode_jwt_payload(jwt)

    account_id =
      get_in(claims, ["https://api.openai.com/auth", "chatgpt_account_id"]) ||
        claims["chatgpt_account_id"] ||
        get_first_org_id(claims)

    <<_first, _rest::binary>> = account_id
    account_id
  end

  defp parse_interval(nil), do: 5
  defp parse_interval(val) when is_integer(val), do: val

  defp parse_interval(val) when is_binary(val) do
    case Integer.parse(val) do
      {n, _} -> n
      :error -> 5
    end
  end

  defp parse_interval(_), do: 5

  defp decode_jwt_payload(jwt) do
    case String.split(jwt, ".") do
      [_header, payload, _signature] ->
        # Add padding if necessary for base64url decoding
        padded = pad_base64url(payload)

        case Base.url_decode64(padded, padding: false) do
          {:ok, json} -> Jason.decode(json)
          :error -> {:error, :invalid_base64}
        end

      _ ->
        {:error, :invalid_jwt}
    end
  end

  defp pad_base64url(str) do
    case rem(byte_size(str), 4) do
      2 -> str <> "=="
      3 -> str <> "="
      _ -> str
    end
  end

  defp get_first_org_id(%{"organizations" => [%{"id" => id} | _]}) when is_binary(id), do: id
  defp get_first_org_id(_), do: nil
end
